title: Tilia Translations di Angela Brisotto
logo: /assets/img/Pagina corsi di aggiornamento.png
description: Corsi di aggiornamento
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
